brances:
  only:
    - 'master'

language: ruby
rvm:
  - 2.1.2

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/social.example.yml config/social.yml
  - psql -c 'create database sc2_test;' -U postgres
  - psql -c 'create database sc2_test_stub;' -U postgres

before_install:
  - sudo apt-get install freetds-dev freetds-bin tdsodbc

