common: &common
  adapter: postgresql
  encoding: utf8
  pool: 10
  host: localhost
  username: postgres
  password: '123'

development:
  <<: *common
  database: sc2_development

test:
  <<: *common
  database: sc2_test

production:
  <<: *common
  database: sc2_production

sc2_md:
  adapter: sqlserver
  mode: dblib
  dataserver: dbserver.example.com
  database: db_name
  username: db_user
  password: password
  timeout: 5000
  encoding: utf8
